name: NLG-Arxiv-AbstractGenerator
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pandas
  - cpuonly
  - torchvision==0.13.0
  - pytorch==1.12.0
  - torchaudio==0.12.0
  - scikit-learn
  - pip
  - pip:
      - streamlit==1.15.2
      - transformers==4.20.1
